import { Header } from "@/components/ui-ud/ui";
import "./globals.css";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "E-Message",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={/*inter.className*/ "min-h-screen"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
